import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nexus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo à <i>Nexus</i>
        </h1>

        <span className={styles.description}>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam, quidem cupiditate nihil, natus, praesentium ipsam doloremque cumque id doloribus odio vero. Laboriosam atque provident cum amet tempore accusantium in repellat.
        </span>

        <div className={styles.grid}>
          <a href="./documentation" className={styles.card}>
            <h2>Documentação &rarr;</h2>
            <span>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cumque, possimus?.</span>
          </a>

          <a href="./history" className={styles.card}>
            <h2>Conheça mais... &rarr;</h2>
            <span>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cumque, possimus?.</span>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/NicolasKurz67"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by Nícolas Kurz
        </a>
      </footer>
    </div>
  )
}
